"""Kirchhoff DKQ and Reissner-Mindlin Q4/MITC4 plate core."""

from .assembly import (
    AssembledPlateSystem,
    LinearSolution,
    assemble_boundary_load,
    assemble_plate_system,
    assemble_system,
    clamped_dofs,
    hard_simply_supported_dofs,
    solve_dirichlet,
    soft_simply_supported_dofs,
    symmetry_dofs,
)
from .boundary import (
    LocalConstraintSolution,
    edge_angle,
    global_dof_transform,
    local_edge_constraints,
    nodal_rotation_transform,
    solve_with_local_constraints,
    transform_system_to_local,
)
from .benchmarks import (
    SinusoidalSolution,
    simply_supported_sinusoidal_solution,
    sinusoidal_load,
)
from .element import (
    ElementMatrices,
    ElementResponse,
    dkq_element_matrices,
    element_response,
    plate_element_matrices,
    q4_consistent_load,
    q4_edge_consistent_load,
    q4_element_matrices,
)
from .kirchhoff import dkq_bending_B, dkq_kinematic_matrices, q8_shape_functions
from .kinematics import generalized_strains, small_strains_at_z, displacement_at_z
from .material import MindlinMaterial
from .mesh import BoundaryEdge, Mesh, exterior_edges, rectangular_mesh, select_exterior_edges
from .postprocess import (
    RecoveredElement,
    RecoveredPoint,
    recover_element_centers,
    recover_element_gauss_points,
    recover_element_points,
    split_nodal_dofs,
)
from .q4 import kinematic_matrices, mitc4_shear_B, shape_functions
from .service import (
    MAX_SERVICE_DOFS,
    PlateAnalysis,
    PlateInputError,
    serialize_analysis,
    solve_plate_case,
)
from .theory import (
    DEFAULT_THINNESS_RATIO,
    PlateMethod,
    PlateMethodRequest,
    PlateMethodSelection,
    choose_plate_method,
    normalize_plate_method,
    plate_characteristic_length,
    select_plate_method,
)
from .validation import (
    CoreValidationReport,
    DistortionComparison,
    ElementSpectrum,
    PatchTestResult,
    ThicknessScanRow,
    constant_shear_patch_test,
    element_spectrum,
    run_core_validation,
    square_distortion_comparison,
    square_thickness_scan,
)

__all__ = [
    "AssembledPlateSystem",
    "BoundaryEdge",
    "CoreValidationReport",
    "DEFAULT_THINNESS_RATIO",
    "DistortionComparison",
    "ElementMatrices",
    "ElementResponse",
    "ElementSpectrum",
    "LinearSolution",
    "LocalConstraintSolution",
    "MAX_SERVICE_DOFS",
    "Mesh",
    "MindlinMaterial",
    "PatchTestResult",
    "PlateMethod",
    "PlateMethodRequest",
    "PlateMethodSelection",
    "PlateAnalysis",
    "PlateInputError",
    "RecoveredElement",
    "RecoveredPoint",
    "SinusoidalSolution",
    "ThicknessScanRow",
    "assemble_boundary_load",
    "assemble_plate_system",
    "assemble_system",
    "choose_plate_method",
    "clamped_dofs",
    "constant_shear_patch_test",
    "displacement_at_z",
    "dkq_bending_B",
    "dkq_element_matrices",
    "dkq_kinematic_matrices",
    "edge_angle",
    "element_response",
    "element_spectrum",
    "exterior_edges",
    "generalized_strains",
    "global_dof_transform",
    "hard_simply_supported_dofs",
    "kinematic_matrices",
    "local_edge_constraints",
    "mitc4_shear_B",
    "nodal_rotation_transform",
    "normalize_plate_method",
    "plate_characteristic_length",
    "plate_element_matrices",
    "q4_consistent_load",
    "q4_edge_consistent_load",
    "q4_element_matrices",
    "q8_shape_functions",
    "recover_element_centers",
    "recover_element_gauss_points",
    "recover_element_points",
    "rectangular_mesh",
    "select_exterior_edges",
    "select_plate_method",
    "serialize_analysis",
    "shape_functions",
    "simply_supported_sinusoidal_solution",
    "sinusoidal_load",
    "small_strains_at_z",
    "soft_simply_supported_dofs",
    "solve_dirichlet",
    "solve_plate_case",
    "solve_with_local_constraints",
    "split_nodal_dofs",
    "square_distortion_comparison",
    "square_thickness_scan",
    "symmetry_dofs",
    "transform_system_to_local",
    "run_core_validation",
]
